theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  logo:
    header: "/assets/images/logoLGVEA.png"
    footer: "/assets/images/logoLGVEA.png"
  plausible: lgvea.fr
  summary:
    position: hero
  search:
    active: false  
  debug:
     productionUrl: "https://www.lgvea.fr"
