theme: osuny
_merge: deep
params:
  logo:
    header: "/assets/images/logoLGVEA.png"
    footer: "/assets/images/logoLGVEA.png"
  plausible: lgvea.fr
  summary:
    position: hero
  search:
    active: false  
  debug:
     productionUrl: "https://www.lgvea.fr"
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
      